### ISSUE TITLE
Timeout priklausomybė nuo failo ilgio

### ISSUE THREAD

**Issue by gailius-r** [airenas/list_transcriber#2]
20 sek "timeout'as" buvo per mažas 1h trukmės įrašams siųsti. Kode lokaliai pakeičiau 20 s į 120 s - tada paslauga praėjo. Vertėtų pagalvoti ar "tiemout'as" neturėtų būti parenkamas kaip funkcija nuo siunčiamo failo ilgio. Tada vartotojui nereikėtų tuo rūpintis

**Comment by airenas** [comment]
Gal, bet neverta, padidinau timeout ir tiek
